#!/usr/bin/env bash
set -euo pipefail
rm -rf dist/pypi && mkdir -p dist/release dist/pypi
pip install ".[dev]" build twine
python -m build --outdir dist/pypi
python -m twine check dist/pypi/*
cp dist/pypi/* dist/release/
